# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NOOK_BOT: ${{ secrets.NOOK_BOT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Run tests
      run: ./gradlew jacocoTestReport
    - name: Run detekt with reviewdog
      uses: gumil/Detekt-Action@v0.1.2
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detekt_config: config/detekt/detekt.yml
    - uses: codecov/codecov-action@v1
      with:
        file: core/build/reports/jacocoTestReport.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
